### ISSUE TITLE
无法启动GUI程序

### ISSUE THREAD

**Issue by fate-ubw** [FFengIll/pdf-cut-white#10]
# 遇到的问题：我直接打开pycharm，并且已经安装了全部需要的python库，但是一九无法启动程序
# 报错截图：
![image](https://user-images.githubusercontent.com/57163791/192074181-fdd83150-9cf6-4fc6-bee9-b95378c71f9a.png)
# 可能的问题：
+ 报错是无法打开cutter，不知道是不是需要把其他py文件放到一个文件夹下面运行
非常好的程序，希望可以得到解答，谢谢

**Comment by FFengIll** [comment]
推荐用命令行版本运行。
一是因为UI当时的版本很老了，现在不一定适用。
二是因为后续大家没有用过GUI版本，所以也没再维护GUI。

建议先命令行解决目前的需求，GUI得空时我来看看~

**Comment by FFengIll** [comment]
试了下，应当是PySide有所变化。
可以更新并参阅下（新的）README，更新到PySide6使用。

**Comment by FFengIll** [comment]
另，从截图来看，是有依赖没有安装，我同步更新下requirements，请尝试重新`pip install -r requirements.txt`

**Comment by fate-ubw** [comment]
非常感谢，问题已经得到了解决，对我的项目有很大的帮助
