### ISSUE TITLE
Error: use default for error: 'LTImage' object has no attribute '_objs'

### ISSUE THREAD

**Issue by zengchang233** [FFengIll/pdf-cut-white#11]
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/35031709/197946155-cc1a1cc0-e02c-47a5-b962-fed12c31e2b4.png">

Hello, it seems there is a bug when working on my pdf file. Could you have a check? Thanks

**Comment by FFengIll** [comment]
could you pls provide a sample file to help debug?

**Comment by FFengIll** [comment]
Furthermore, this `Error` log is only a notice and do not break pdf process logic.
It may output unwanted result since it ignores these PDF items.
