### ISSUE TITLE
你好，提示出错了，这个怎么解决呀

### ISSUE THREAD

**Issue by wlioi** [FFengIll/pdf-cut-white#22]
Python升级到最新了

024-09-01 22:14:30.821 | INFO     | pdf_white_cut.worker:cut_page_box:58 - cut media box to: Rect(0.0, 0.0, 595.0, 841.0)
2024-09-01 22:14:30.823 | INFO     | pdf_white_cut.worker:cut_pdf:115 - output to I:\iDownloads\pdf-cut-white-master\春 琴抄已裁剪.pdf
2024-09-01 22:14:30.826 | ERROR    | pdf_white_cut.worker:cut_pdf:126 - Some unknown Error while processing file:I:\iDownloads\pdf-cut-white-master\春琴抄.pdf
Traceback (most recent call last):

  File "I:\iDownloads\pdf-cut-white-master\cli.py", line 16, in <module>
    cut_pdf(args.input, args.output, args.ignore)
    │       │    │      │    │       │    └ 0
    │       │    │      │    │       └ Namespace(input='I:\\iDownloads\\pdf-cut-white-master\\春琴抄.pdf', output='I:\\iDownloads\\pdf-cut-white-master\\春琴抄已裁剪.pdf', i...
    │       │    │      │    └ 'I:\\iDownloads\\pdf-cut-white-master\\春琴抄已裁剪.pdf'
    │       │    │      └ Namespace(input='I:\\iDownloads\\pdf-cut-white-master\\春琴抄.pdf', output='I:\\iDownloads\\pdf-cut-white-master\\春琴抄已裁剪.pdf', i...
    │       │    └ 'I:\\iDownloads\\pdf-cut-white-master\\春琴抄.pdf'
    │       └ Namespace(input='I:\\iDownloads\\pdf-cut-white-master\\春琴抄.pdf', output='I:\\iDownloads\\pdf-cut-white-master\\春琴抄已裁剪.pdf', i...
    └ <function cut_pdf at 0x000001D94BBC3F60>

> File "I:\iDownloads\pdf-cut-white-master\pdf_white_cut\worker.py", line 116, in cut_pdf
    target.abspath().dirname().makedirs_p()
    └ Path('I:\\iDownloads\\pdf-cut-white-master\\春琴抄已裁剪.pdf')

AttributeError: 'Path' object has no attribute 'abspath'
2024-09-01 22:14:30.851 | ERROR    | pdf_white_cut.worker:cut_pdf:127 - 'Path' object has no attribute 'abspath'
Traceback (most recent call last):

  File "I:\iDownloads\pdf-cut-white-master\cli.py", line 16, in <module>
    cut_pdf(args.input, args.output, args.ignore)
    │       │    │      │    │       │    └ 0
    │       │    │      │    │       └ Namespace(input='I:\\iDownloads\\pdf-cut-white-master\\春琴抄.pdf', output='I:\\iDownloads\\pdf-cut-white-master\\春琴抄已裁剪.pdf', i...
    │       │    │      │    └ 'I:\\iDownloads\\pdf-cut-white-master\\春琴抄已裁剪.pdf'
    │       │    │      └ Namespace(input='I:\\iDownloads\\pdf-cut-white-master\\春琴抄.pdf', output='I:\\iDownloads\\pdf-cut-white-master\\春琴抄已裁剪.pdf', i...
    │       │    └ 'I:\\iDownloads\\pdf-cut-white-master\\春琴抄.pdf'
    │       └ Namespace(input='I:\\iDownloads\\pdf-cut-white-master\\春琴抄.pdf', output='I:\\iDownloads\\pdf-cut-white-master\\春琴抄已裁剪.pdf', i...
    └ <function cut_pdf at 0x000001D94BBC3F60>

> File "I:\iDownloads\pdf-cut-white-master\pdf_white_cut\worker.py", line 116, in cut_pdf
    target.abspath().dirname().makedirs_p()
    └ Path('I:\\iDownloads\\pdf-cut-white-master\\春琴抄已裁剪.pdf')

AttributeError: 'Path' object has no attribute 'abspath'
2024-09-01 22:14:30.869 | ERROR    | __main__:<module>:22 - 'Path' object has no attribute 'abspath'
Traceback (most recent call last):

> File "I:\iDownloads\pdf-cut-white-master\cli.py", line 16, in <module>
    cut_pdf(args.input, args.output, args.ignore)
    │       │    │      │    │       │    └ 0
    │       │    │      │    │       └ Namespace(input='I:\\iDownloads\\pdf-cut-white-master\\春琴抄.pdf', output='I:\\iDownloads\\pdf-cut-white-master\\春琴抄已裁剪.pdf', i...
    │       │    │      │    └ 'I:\\iDownloads\\pdf-cut-white-master\\春琴抄已裁剪.pdf'
    │       │    │      └ Namespace(input='I:\\iDownloads\\pdf-cut-white-master\\春琴抄.pdf', output='I:\\iDownloads\\pdf-cut-white-master\\春琴抄已裁剪.pdf', i...
    │       │    └ 'I:\\iDownloads\\pdf-cut-white-master\\春琴抄.pdf'
    │       └ Namespace(input='I:\\iDownloads\\pdf-cut-white-master\\春琴抄.pdf', output='I:\\iDownloads\\pdf-cut-white-master\\春琴抄已裁剪.pdf', i...
    └ <function cut_pdf at 0x000001D94BBC3F60>

  File "I:\iDownloads\pdf-cut-white-master\pdf_white_cut\worker.py", line 128, in cut_pdf
    raise e

  File "I:\iDownloads\pdf-cut-white-master\pdf_white_cut\worker.py", line 116, in cut_pdf
    target.abspath().dirname().makedirs_p()
    └ Path('I:\\iDownloads\\pdf-cut-white-master\\春琴抄已裁剪.pdf')

AttributeError: 'Path' object has no attribute 'abspath'

I:\iDownloads\pdf-cut-white-master>

**Comment by FFengIll** [comment]
从日志看是Path这个包升级了，有一些变化。
这个需要检查下。

**Comment by FFengIll** [comment]
已更新，请重新git pull并按文档安装使用。

**Comment by TheRainstorm** [comment]
仍然存在问题

Environments:

Python 3.10.12
package path 17.0.0
➜  pdf-cut-white git:(master) ✗ python cli.py -id /mnt/Disk1/Workspace/images -od /mnt/Disk1/Workspace/images_pdf_cut --ignore 1
2024-11-30 21:50:31.680 | INFO     | pdf_white_cut.worker:batch_cut_pdf:144 - input dir: /mnt/Disk1/Workspace/images
2024-11-30 21:50:31.680 | INFO     | pdf_white_cut.worker:batch_cut_pdf:145 - output dir: /mnt/Disk1/Workspace/images_pdf_cut
2024-11-30 21:50:31.680 | ERROR    | __main__:<module>:22 - 'Path' object has no attribute 'listdir'
Traceback (most recent call last):

> File "/home/yfy/app/pdf-cut-white/cli.py", line 18, in <module>
    batch_cut_pdf(args.indir, args.outdir, args.ignore)
    │             │    │      │    │       │    └ 1
    │             │    │      │    │       └ Namespace(input='', output='output.pdf', indir='/mnt/Disk1/Workspace/images', outdir='/mnt/Disk1/Workspace/images_pdf_cut', t...
    │             │    │      │    └ '/mnt/Disk1/Workspace/images_pdf_cut'
    │             │    │      └ Namespace(input='', output='output.pdf', indir='/mnt/Disk1/Workspace/images', outdir='/mnt/Disk1/Workspace/images_pdf_cut', t...
    │             │    └ '/mnt/Disk1/Workspace/images'
    │             └ Namespace(input='', output='output.pdf', indir='/mnt/Disk1/Workspace/images', outdir='/mnt/Disk1/Workspace/images_pdf_cut', t...
    └ <function batch_cut_pdf at 0x7c582dbbfb50>

  File "/home/yfy/app/pdf-cut-white/pdf_white_cut/worker.py", line 148, in batch_cut_pdf
    files = [pdf.basename() for pdf in indir.listdir("*.pdf")]
                                       └ Path('/mnt/Disk1/Workspace/images')

AttributeError: 'Path' object has no attribute 'listdir'. Did you mean: 'is_dir'?

修复很简单，我直接提交了一个 pr 了

**Comment by FFengIll** [comment]
Thx, I've reviewed and it is merged.
