### ISSUE TITLE
我测试了下个别场景裁剪不如 texlive 自带的pdfcrop

### ISSUE THREAD

**Issue by latexstudio** [FFengIll/pdf-cut-white#26]
[seqsel.pdf](https://github.com/user-attachments/files/18048982/seqsel.pdf)
附上的文件 pdfcrop 可以裁掉 右边的空白，而工具裁剪似乎没有变化，可以测试下。工作想法很不错。

**Comment by FFengIll** [comment]
这是已知问题，并需要人工配置参数，详见

https://github.com/FFengIll/pdf-cut-white?tab=readme-ov-file#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
https://github.com/FFengIll/pdf-cut-white/issues/4

**Comment by FFengIll** [comment]
这里需要提及：原理上和pdfcrop有较大的差异。
后者基于ghostscript 定位 bbox，并不会顾忌更细节的elem，在使用场景上其实是有所不同的。

> https://pdfcrop.sourceforge.net/
