### ISSUE TITLE
一些pdf会裁剪过度

### ISSUE THREAD

**Issue by chenxiaofei-cxf** [FFengIll/pdf-cut-white#6]
![image](https://user-images.githubusercontent.com/21291528/117028399-44d86580-ad30-11eb-9f16-840572685d8c.png)

裁剪后：
![image](https://user-images.githubusercontent.com/21291528/117028067-ea3f0980-ad2f-11eb-9205-ef60362d5c4f.png)
 把很多字裁没了
[exp7_drop.pdf](https://github.com/FFengIll/pdf-cut-white/files/6422150/exp7_drop.pdf)

**Comment by FFengIll** [comment]
sorry，之前遗漏了这个issue。
我近期会看一看。

**Comment by FFengIll** [comment]
最终定位原因是 没有处理Literal Box这种情况（即文本框）。
最初实现时没有这样的遭遇，所以忽视了。

**Comment by FFengIll** [comment]
Literal 需要 在box的基础上，额外处理 y1 （left lower），即对应需要扣除literal 的height值。
目前已对应修正 e4522d39e6b4b205d27f8befa42d6a11c1999c1d 
https://github.com/FFengIll/pdf-cut-white/commit/e4522d39e6b4b205d27f8befa42d6a11c1999c1d#r56006481
